[package]
name = "bandsocks"
version = "0.1.0"
description = "Experimental embeddable container sandbox (not working yet)"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/scanlime/bandsocks"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.11"
clap = { version = "2.33.3", features = ["yaml"] }
bandsocks-runtime = { path = "runtime" }
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }

[workspace]
members = [ "runtime" ]
