[package]
name = "bandsocks"
version = "0.2.0"
description = "Experimental embeddable container sandbox (not working yet)"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/scanlime/bandsocks"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]

# Extra deps for the command line binary
env_logger = "0.7.1"
clap = { version = "2.33.3", features = ["yaml"] }

# Sandbox internals are a separate workspace with a separate (nested) build
bandsocks-sand = { path = "sand" }

# Runtime library dependencies
log = "0.4.11"
tokio = { version = "0.2.22", features = ["rt-core", "fs", "macros"] }
directories-next = "1.0.1"
dkregistry = "0.5.0"
fd-queue = { version = "1.0.0-beta.2", features = [ "tokio-fd" ] }
flate2 = "1.0.17"
lazy_static = "1.4.0"
libc = "0.2.78"
hash32 = "0.1.0"
hash32-derive = "0.1.0"
heapless = "0.5.6"
memmap = "0.7.0"
osstrtools = "0.2.2"
pentacle = "1.0.0"
regex = "1.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
sha2 = "0.9.1"
tar = "0.4.30"
thiserror = "1.0"

[build-dependencies]
build-deps = "0.1.4"
