[package]
name = "bandsocks"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.11"
clap = { version = "2.33.3", features = ["yaml"] }
bandsocks-runtime = { path = "runtime" }

[workspace]
members = [ "runtime", "sand" ]
