[package]
name = "bandsocks-runtime"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]

log = "0.4.11"
vfs = "0.4.0"
pentacle = "0.2.0"
pete = "0.3.0"
dkregistry = { git = "https://github.com/camallo/dkregistry-rs.git" }
memmap = "0.7.0"
libc = "0.2.77"
tar = "0.4.30"
tokio = "0.2.22"
thiserror = "1.0"
