[package]
name = "bandsocks-sand"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]

compiler_builtins = { version = "0.1.36", features = [ "compiler-builtins", "mem" ] }
memoffset = "0.5.6"
seccomp-tiny = "0.1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sc = "0.2.3"
ssmarshal = { version = "1.0.0", default-features = false }

[workspace]
# Separate workspace, with our own build profiles:

[profile.release]
lto = 'fat'
codegen-units = 1
incremental = false
panic = 'abort'
opt-level = 's'

[profile.dev]
lto = 'fat'
codegen-units = 1
incremental = false
panic = 'abort'
opt-level = 's'
