[package]
name = "bandsocks-sand"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]

sc = "0.2.3"

[workspace]
# Separate workspace, with our own build profiles:

[profile.release]
lto = true
panic = 'abort'
opt-level = 's'

[profile.dev]
lto = true
panic = 'abort'
opt-level = 's'
