cargo-features = ["strip"]

[package]
name = "bandsocks-sand"
version = "0.2.0"
description = "Internal runtime binary for bandsocks"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/scanlime/bandsocks"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]

as-slice = "0.1"
bandsocks-protocol = { version = "0.2", path = "protocol" }
compiler_builtins = { version = "0.1", features = [ "compiler-builtins", "mem" ] }
generic-array = "0.14"
goblin = { version = "0.2", default-features = false, features = ["elf64"] }
hash32 = "0.1"
heapless = "0.5"
memoffset = "0.5"
pin-project = "1"
plain = "0.2"
raw-cpuid = "8.1"
sc = "0.2"
seccomp-tiny = "0.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
smalloca = { version = "0.1", default-features = false }
twoway = { version = "0.2", default-features = false }
typenum = "1.12"

[dev-dependencies]
file_limit = "0.0"

[workspace]
members = ["protocol"]

[profile.release]
lto = 'fat'
codegen-units = 1
incremental = false
panic = 'abort'
opt-level = 's'
strip = 'symbols'

[profile.dev]
lto = 'fat'
codegen-units = 1
incremental = false
panic = 'abort'
opt-level = 's'
strip = 'symbols'

